export { Navbar } from "./navbar";
export { Hero } from "./hero";
export { Features } from "./features";
export { HowItWorks } from "./how-it-works";
export { Pricing } from "./pricing";
export { CTA } from "./cta";
export { Footer } from "./footer";
export { TypingText } from "./typing-text";
export { FadeInOnScroll } from "./fade-in-on-scroll";
